- name: Manage Repositories and Update RHEL 8
  hosts: trg
  become: true
  vars_files:
    - ../vaults/sudo_pass.yml
  vars:
    ansible_become_pass: "{{ sudo_passwords.all_password }}"
  tasks:
    - name: Create a local repository configuration file
      copy:
        dest: /etc/yum.repos.d/rhel8-local.repo
        content: |
          [rhel-8-baseos]
          name=RHEL8 BaseOS RPMs
          enabled=1
          gpgcheck=0
          baseurl=http://172.24.197.16/rhel8/rhel-8-for-x86_64-baseos-rpms/

          [rhel-8-appstream]
          name=RHEL8 AppStream RPMs
          enabled=1
          gpgcheck=0
          baseurl=http://172.24.197.16/rhel8/rhel-8-for-x86_64-appstream-rpms/
      tags: repo_url

    - name: verify the local mirrior repo
      shell: yum repolist
      register: status

    - name: retrieve the repo list
      debug:
         msg: "{{ status.stdout_lines }}"

